//! Deterministic static generation of the verified record (SPEC.md §10).
//!
//! The whole tree is a pure function of (immutable registry rows, the pin, the
//! generator version) plus one further, named input class — the profile identity
//! rows behind `u/<login>/`, `profiles*.json` and `_redirects.json`, which is why
//! a rename enqueues a regeneration rather than being left to drift. No clock,
//! no RNG, no map iteration order, no login inside `[data-region="verified"]`,
//! no note and no asset hash reaches a page, so two runs over an unchanged
//! registry produce byte-identical output and `recordgen --check` cannot alarm
//! on an ordinary note edit.

pub mod about;
pub mod doc;
pub mod html;
pub mod jsonc;
pub mod leak;
pub mod model;
pub mod pages;
pub mod reasons;
pub mod release;
pub mod search;
pub mod snapshot;

use accession::{Accession, Kind, citation};
use html::B;
use jsonc::{canonical, canonical_line, ts};
use search::BankRow;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// The generator's input, at the crate root because a caller that already holds
/// the rows renders them through `generate_snapshot` without a second read.
///
/// `Snapshot` replaces the scaffold's `GenInput`. It is the same set of rows
/// plus the two the contract added — the profile login history behind
/// `_redirects.json`, and the About body, which is read and scanned by
/// `Snapshot::load` rather than passed in already trusted. A caller that built a
/// `GenInput` builds a `Snapshot` instead and calls `generate_snapshot(&s, out,
/// &opts)`; a caller that has a `Store` calls `generate` and builds neither.
pub use snapshot::{ArgumentView, Redirect, Snapshot};

/// The generator's own version: one of the three inputs `#record`'s bytes are a
/// function of, and the only build identifier any file in the tree carries.
pub const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

/// The marker that says a tree is the legacy internal corpus. Every public
/// binary refuses to run under it (SPEC.md §10, mechanism 1).
pub const INTERNAL_MARKER: &str = ".internal-corpus";

#[derive(Debug, thiserror::Error)]
pub enum GenError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("registry: {file}{pointer} is not a record this tree can render")]
    RegistryInvalid { file: String, pointer: String },
    #[error("leak: {file}@{offset} carries `{term}`")]
    LeakFound {
        file: String,
        offset: usize,
        term: String,
    },
    #[error("about/body.html@{offset}: {reason}")]
    AboutBodyRejected { offset: usize, reason: String },
    #[error("the DOI index is shorter than the generation it would replace")]
    DoiIndexShrank,
    #[error("refusing: internal corpus marker present")]
    InternalMarkerPresent,
    #[error("drift in {} files", files.len())]
    Drift { files: Vec<String> },
    #[error("search: {0}")]
    Search(#[from] search::SearchError),
    #[error("serialize: {0}")]
    Serialize(#[from] serde_json::Error),
}

#[derive(Debug, Clone)]
pub struct GenOpts {
    /// The public origin every baked citation resolves through.
    pub site_base: String,
    /// The path the record is served under (`/mathesis-bank` on a project
    /// site, empty at a domain root). Every root-relative URL a page carries
    /// is prefixed with it.
    pub base_path: String,
    /// The git-tracked `about/body.html`. `None` is the empty shell.
    pub about_body: Option<PathBuf>,
    /// The forum's public origin and path. Each post links out to its page
    /// there, `{forum_base}/p/{argument accession}/`; `None` links nowhere.
    /// Discussion is the forum's, never the record's.
    pub forum_base: Option<String>,
    /// Write a release beside `out` and publish it by renaming a symlink.
    pub atomic: bool,
    /// Walk every generated byte for the internal corpus.
    pub leak_scan: bool,
    /// Refuse a generation that drops a DOI the live tree already serves.
    pub guard_monotone: bool,
    /// Generate to a temporary tree and diff it against the live one instead of
    /// publishing: `recordgen --check`.
    pub check: bool,
}

impl Default for GenOpts {
    fn default() -> Self {
        GenOpts {
            site_base: "https://mathesis.localtest.me".into(),
            base_path: String::new(),
            about_body: None,
            forum_base: None,
            atomic: false,
            leak_scan: true,
            guard_monotone: false,
            check: false,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize, PartialEq, Eq)]
pub struct FileDigest {
    pub sha256: String,
    pub bytes: u64,
}

#[derive(Debug, Clone, Default, serde::Serialize, PartialEq, Eq)]
pub struct Counts {
    pub claims: usize,
    pub arguments: usize,
    pub posts: usize,
    pub profiles: usize,
    pub pages: usize,
    pub accessions: usize,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct RecordManifest {
    pub generator_version: String,
    pub record_digest: String,
    pub dictionary_pin: String,
    pub counts: Counts,
    pub files: BTreeMap<String, FileDigest>,
    /// The directory the generation was written to. Not part of `index.json`:
    /// a release name is an operational fact, not a record one.
    #[serde(skip)]
    pub release: PathBuf,
}

// ----------------------------------------------------------------- the writer

struct Writer {
    root: PathBuf,
    base_path: String,
    /// The nav's `Profile` target: before sign-in exists, the profile the
    /// record is published under.
    profile_href: Option<String>,
    files: BTreeMap<String, FileDigest>,
    pages: usize,
    leak_scan: bool,
    local_terms: Vec<String>,
}

impl Writer {
    fn put(&mut self, rel: &str, bytes: &[u8]) -> Result<(), GenError> {
        if self.leak_scan {
            let html = rel.ends_with(".html");
            if let Ok(text) = std::str::from_utf8(bytes) {
                if let Some(h) = leak::scan(text, &self.local_terms, html) {
                    return Err(GenError::LeakFound {
                        file: rel.to_string(),
                        offset: h.offset,
                        term: h.term,
                    });
                }
            }
        }
        let path = self.root.join(rel);
        if let Some(p) = path.parent() {
            std::fs::create_dir_all(p)?;
        }
        std::fs::write(&path, bytes)?;
        let mut h = Sha256::new();
        h.update(bytes);
        self.files.insert(
            rel.to_string(),
            FileDigest {
                sha256: format!("{:x}", h.finalize()),
                bytes: bytes.len() as u64,
            },
        );
        if rel.ends_with(".html") {
            self.pages += 1;
        }
        Ok(())
    }

    /// One page and the `{field,value}` array `prose-lint` checks its rendered
    /// values against, emitted by the same pass that rendered them (R40).
    fn page(&mut self, rel: &str, page: &str, b: &B) -> Result<(), GenError> {
        let html = pages::with_base(
            &pages::shell(page, &b.s, self.profile_href.as_deref()),
            &self.base_path,
        );
        self.put(rel, html.as_bytes())?;
        let values = rel
            .strip_suffix("index.html")
            .map(|d| format!("{d}values.json"))
            .unwrap_or_else(|| format!("{}.values.json", rel.trim_end_matches(".html")));
        self.put(&values, b.values_json().as_bytes())
    }
}

// -------------------------------------------------------------------- the API

pub fn generate_snapshot(
    s: &Snapshot,
    out: &Path,
    opts: &GenOpts,
) -> Result<RecordManifest, GenError> {
    guard_marker(out)?;

    let live = if opts.atomic {
        release::live(out)
    } else {
        Some(out.to_path_buf())
    };
    // The DOI index the live tree serves, read before anything is written: in
    // the non-atomic form the generation overwrites the tree it is compared
    // against, so the guard cannot read it afterwards.
    let previous_dois = live
        .as_deref()
        .map(|l| std::fs::read_to_string(l.join("doi/index.jsonl")).unwrap_or_default())
        .unwrap_or_default();
    let target = if opts.check {
        let dir = out.with_extension(format!("check.{}", std::process::id()));
        if dir.exists() {
            std::fs::remove_dir_all(&dir)?;
        }
        std::fs::create_dir_all(&dir)?;
        dir
    } else if opts.atomic {
        release::next(out)?
    } else {
        if out.exists() && release::live(out).is_none() {
            std::fs::remove_dir_all(out)?;
        }
        std::fs::create_dir_all(out)?;
        out.to_path_buf()
    };

    let result = render(s, &target, opts, live.as_deref(), &previous_dois);
    match result {
        Ok(manifest) => {
            if opts.check {
                let drift = diff(&target, live.as_deref())?;
                std::fs::remove_dir_all(&target)?;
                if !drift.is_empty() {
                    return Err(GenError::Drift { files: drift });
                }
                return Ok(RecordManifest {
                    release: PathBuf::new(),
                    ..manifest
                });
            }
            if opts.atomic {
                release::swap(out, &target)?;
                release::prune(out)?;
            }
            Ok(manifest)
        }
        Err(e) => {
            // A failed generation never touches the live tree.
            if opts.check || opts.atomic {
                let _ = std::fs::remove_dir_all(&target);
            }
            Err(e)
        }
    }
}

fn guard_marker(out: &Path) -> Result<(), GenError> {
    let mut here = Some(out.to_path_buf());
    let mut depth = 0;
    while let Some(p) = here {
        if p.join(INTERNAL_MARKER).exists() {
            return Err(GenError::InternalMarkerPresent);
        }
        depth += 1;
        if depth > 2 {
            break;
        }
        here = p.parent().map(Path::to_path_buf);
    }
    Ok(())
}

fn diff(fresh: &Path, live: Option<&Path>) -> Result<Vec<String>, GenError> {
    let Some(live) = live else {
        return Ok(vec!["<no live tree>".into()]);
    };
    let mut out = Vec::new();
    let a = walk(fresh)?;
    let b = walk(live)?;
    for (rel, bytes) in &a {
        match b.get(rel) {
            Some(other) if other == bytes => {}
            _ => out.push(rel.clone()),
        }
    }
    for rel in b.keys() {
        if !a.contains_key(rel) {
            out.push(rel.clone());
        }
    }
    out.sort();
    out.dedup();
    Ok(out)
}

/// Every file of a tree except the search index, whose segment identifiers are
/// randomly generated by Tantivy and are therefore not a determinism claim this
/// crate can make. The index is derived from `collection/*.json`, which are
/// diffed, so a difference in the banks is still caught.
fn walk(root: &Path) -> Result<BTreeMap<String, Vec<u8>>, GenError> {
    let mut out = BTreeMap::new();
    fn rec(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) -> std::io::Result<()> {
        for e in std::fs::read_dir(dir)? {
            let e = e?;
            let p = e.path();
            if p.is_dir() {
                rec(root, &p, out)?;
            } else {
                let rel = p.strip_prefix(root).unwrap().to_string_lossy().into_owned();
                if rel.starts_with("search/") {
                    continue;
                }
                out.insert(rel, std::fs::read(&p)?);
            }
        }
        Ok(())
    }
    if root.exists() {
        rec(root, root, &mut out)?;
    }
    Ok(out)
}

// ------------------------------------------------------------- the generation

fn render(
    s: &Snapshot,
    root: &Path,
    opts: &GenOpts,
    _live: Option<&Path>,
    previous_dois: &str,
) -> Result<RecordManifest, GenError> {
    let local_terms = opts
        .about_body
        .as_ref()
        .and_then(|p| p.parent().and_then(Path::parent).map(leak::local_terms))
        .unwrap_or_default();
    let mut w = Writer {
        root: root.to_path_buf(),
        base_path: opts.base_path.trim_end_matches('/').to_string(),
        profile_href: s
            .profiles
            .iter()
            .find(|p| p.is_owner)
            .or(s.profiles.first())
            .map(|p| format!("/u/{}/", p.login)),
        files: BTreeMap::new(),
        pages: 0,
        leak_scan: opts.leak_scan,
        local_terms,
    };

    // ---- the nav pages, the routes that are not nav items ----
    w.page("index.html", "posts", &pages::posts_page(s))?;
    w.page(
        "collection/claims/index.html",
        "collection",
        &pages::collection_page(s, "claims"),
    )?;
    w.page(
        "collection/arguments/index.html",
        "collection",
        &pages::collection_page(s, "arguments"),
    )?;
    w.page("about/index.html", "about", &pages::about_page(s))?;
    w.page("ide/index.html", "ide", &pages::ide_page(s))?;
    for p in &s.profiles {
        let href = format!("/u/{}/", p.login);
        let home = w.profile_href.as_deref() == Some(href.as_str());
        w.page(
            &format!("u/{}/index.html", p.login),
            "profile",
            &pages::profile_page(s, p, home),
        )?;
    }

    let not_found = pages::not_found_page();
    w.page("404.html", "404", &not_found)?;
    // The same two documents under the directory form `webd` reads today, so
    // the error pages are served from the record rather than from a Go literal.
    w.page("404/index.html", "404", &not_found)?;

    // ---- one landing page and one manifest per accession ----
    let mut accessions: Vec<Accession> = Vec::new();
    for c in &s.claims {
        accessions.push(c.accession.parse().map_err(|_| GenError::RegistryInvalid {
            file: "claim".into(),
            pointer: format!("/{}/accession", c.accession),
        })?);
    }
    for a in &s.arguments {
        accessions.push(
            a.argument
                .accession
                .parse()
                .map_err(|_| GenError::RegistryInvalid {
                    file: "argument".into(),
                    pointer: format!("/{}/accession", a.argument.accession),
                })?,
        );
    }
    accessions.sort();
    let mut doi_index = String::new();
    for acc in &accessions {
        let key = acc.to_string();
        let page = pages::landing_page(s, &key).ok_or_else(|| GenError::RegistryInvalid {
            file: "accession".into(),
            pointer: format!("/{key}"),
        })?;
        w.page(&format!("a/{key}/index.html"), "landing", &page)?;
        w.put(
            &format!("a/{key}/index.json"),
            canonical(&manifest_for(s, acc))?.as_bytes(),
        )?;
        doi_index.push_str(&canonical_line(&serde_json::json!({
            "doi": key,
            "kind": acc.kind.subject(),
            "subject": acc.kind.subject(),
            "landing": acc.landing_path(),
            "path": acc.landing_path(),
        }))?);
    }
    w.put("doi/index.jsonl", doi_index.as_bytes())?;

    // ---- the stream, paged, newest first ----
    let mut post_rows: Vec<serde_json::Value> = Vec::new();
    for p in &s.posts {
        let Some(a) = s.argument(&p.argument_accession) else {
            continue;
        };
        post_rows.push(serde_json::json!({
            "post_number": p.post_number,
            "claim": p.claim_accession,
            "argument": p.argument_accession,
            "post_url": format!("/a/{}", p.argument_accession),
            "published_at": ts(&p.published_at),
            "author": a.argument.citation_name,
            "author_login": a.argument.login,
        }));
    }
    for (i, chunk) in post_rows.chunks(20).enumerate() {
        let next = post_rows.get((i + 1) * 20).map(|_| {
            let last = &chunk[chunk.len() - 1];
            search::encode_cursor(
                last["post_number"].as_i64().unwrap_or_default(),
                last["argument"].as_str().unwrap_or_default(),
            )
        });
        w.put(
            &format!("posts-{i:04}.json"),
            canonical(&serde_json::json!({
                "page": i,
                "rows": chunk,
                "next_cursor": next,
                "total": post_rows.len(),
            }))?
            .as_bytes(),
        )?;
    }
    if post_rows.is_empty() {
        w.put(
            "posts-0000.json",
            canonical(
                &serde_json::json!({ "page": 0, "rows": [], "next_cursor": null, "total": 0 }),
            )?
            .as_bytes(),
        )?;
    }
    for p in &s.profiles {
        let rows: Vec<&serde_json::Value> = post_rows
            .iter()
            .filter(|r| r["author_login"].as_str() == Some(p.login.as_str()))
            .collect();
        w.put(
            &format!("posts/by-profile/{}.json", p.login),
            canonical(&serde_json::json!({ "login": p.login, "rows": rows, "total": rows.len() }))?
                .as_bytes(),
        )?;
    }

    // ---- the two segregated banks ----
    let claims_rows = bank_rows(s, search::Bank::Claims);
    let arguments_rows = bank_rows(s, search::Bank::Arguments);
    for (bank, rows) in [("claims", &claims_rows), ("arguments", &arguments_rows)] {
        let pages_of: Vec<&[BankRow]> = if rows.is_empty() {
            vec![&[]]
        } else {
            rows.chunks(20).collect()
        };
        for (i, chunk) in pages_of.iter().enumerate() {
            let next = rows.get((i + 1) * 20).map(|_| {
                let last = &chunk[chunk.len() - 1];
                search::encode_cursor(
                    chrono::DateTime::parse_from_rfc3339(&last.created_at)
                        .map(|t| t.timestamp())
                        .unwrap_or(0),
                    &last.accession,
                )
            });
            w.put(
                &format!("collection/{bank}-{i:04}.json"),
                canonical(&search::BankPage {
                    bank: bank.to_string(),
                    page: i,
                    rows: chunk.to_vec(),
                    next_cursor: next,
                    total: rows.len(),
                })?
                .as_bytes(),
            )?;
        }
    }

    // ---- profiles: the filter source, the resolver, the redirects ----
    let mut by_id = String::new();
    let mut combobox = Vec::new();
    for p in &s.profiles {
        by_id.push_str(&canonical_line(
            &serde_json::json!({ "profile_id": p.id.to_string(), "login": p.login }),
        )?);
        combobox.push(serde_json::json!({
            "login": p.login,
            "citation_name": p.citation_name,
            "avatar": p.avatar,
        }));
        let claims: Vec<&model::Claim> = s.claims.iter().filter(|c| c.profile_id == p.id).collect();
        let args: Vec<&ArgumentView> = s
            .arguments
            .iter()
            .filter(|a| a.argument.profile_id == p.id)
            .collect();
        let mut dois: Vec<serde_json::Value> = Vec::new();
        for c in &claims {
            dois.push(serde_json::json!({
                "accession": c.accession, "kind": "claim", "decl_name": c.decl_name,
                "axioms": s.claim_axioms(&c.accession), "arguments": c.arguments_count,
                "verified": ts(&c.created_at),
            }));
        }
        for a in &args {
            dois.push(serde_json::json!({
                "accession": a.argument.accession, "kind": "argument", "decl_name": a.argument.root_decl_name,
                "axioms": a.argument.axioms_reached, "arguments": 1,
                "verified": ts(&a.argument.created_at),
            }));
        }
        w.put(
            &format!("profiles/{}.json", p.login),
            canonical(&serde_json::json!({
                "login": p.login,
                "citation_name": p.citation_name,
                "profile_id": p.id.to_string(),
                "kind": p.kind,
                "created_at": ts(&p.created_at),
                "counts": { "claims": claims.len(), "arguments": args.len(), "posts": args.len(), "dois": dois.len() },
                "dois": dois,
            }))?
            .as_bytes(),
        )?;
    }
    w.put("profiles/by-id.jsonl", by_id.as_bytes())?;
    w.put("profiles.json", canonical(&combobox)?.as_bytes())?;
    w.put("_redirects.json", canonical(&s.redirects)?.as_bytes())?;

    // ---- site.json ----
    let counts = Counts {
        claims: s.claims.len(),
        arguments: s.arguments.len(),
        posts: s.posts.len(),
        profiles: s.profiles.len(),
        pages: w.pages,
        accessions: accessions.len(),
    };
    w.put(
        "site.json",
        canonical(&serde_json::json!({
            "generated_from": {
                "generator_version": GENERATOR_VERSION,
                "dictionary_export_sha256": s.dictionary.export_sha256,
            },
            "dictionary_pin": s.pin_label(),
            "doi_prefix": "MTH.",
            "counts": counts,
        }))?
        .as_bytes(),
    )?;

    // ---- the DOI index may never shrink ----
    if opts.guard_monotone {
        for line in previous_dois.lines().filter(|l| !l.trim().is_empty()) {
            let doi = serde_json::from_str::<serde_json::Value>(line)
                .ok()
                .and_then(|v| v["doi"].as_str().map(str::to_string));
            if let Some(d) = doi {
                if !doi_index.contains(&format!("\"doi\":\"{d}\"")) {
                    return Err(GenError::DoiIndexShrank);
                }
            }
        }
    }

    // ---- the two digests ----
    let mut listing = String::new();
    for (rel, d) in &w.files {
        listing.push_str(&format!("{}  {}\n", d.sha256, rel));
    }
    let mut h = Sha256::new();
    h.update(listing.as_bytes());
    let record_digest = format!("{:x}", h.finalize());

    let manifest = RecordManifest {
        generator_version: GENERATOR_VERSION.to_string(),
        record_digest,
        dictionary_pin: s.pin_label(),
        counts,
        files: w.files.clone(),
        release: root.to_path_buf(),
    };
    w.put("index.json", canonical(&manifest)?.as_bytes())?;

    // `RECORD.sha256` covers `index.json` as well; `index.json` cannot carry its
    // own hash, so the two files are digested in this order and only in it.
    let mut full = String::new();
    for (rel, d) in &w.files {
        full.push_str(&format!("{}  {}\n", d.sha256, rel));
    }
    w.put("RECORD.sha256", full.as_bytes())?;

    Ok(manifest)
}

/// One bank's rows: a claim's three searched fields are its own, an argument's
/// are the denormalized projection of its DAG's single root (SPEC.md §8.3, §10).
fn bank_rows(s: &Snapshot, bank: search::Bank) -> Vec<BankRow> {
    let mut rows = Vec::new();
    match bank {
        search::Bank::Claims => {
            for c in &s.claims {
                let args = s.arguments_of(&c.accession);
                rows.push(BankRow {
                    accession: c.accession.clone(),
                    bank: "claims".into(),
                    decl_name: c.decl_name.clone(),
                    pretty: c.pretty.clone(),
                    module: c.module.clone(),
                    libraries: vec![c.module.clone()],
                    author: c.citation_name.clone(),
                    author_login: c.login.clone(),
                    created_at: ts(&c.created_at),
                    arguments: c.arguments_count as i64,
                    axioms: s.claim_axioms(&c.accession),
                    // `free` on the claims bank means "has at least one
                    // axiom-free argument"; a claim with no argument matches no
                    // axiom filter at all.
                    axiom_free: args.iter().any(|a| a.argument.axiom_free),
                    nodes: 0,
                    constants: 0,
                    claim_accession: None,
                });
            }
        }
        search::Bank::Arguments => {
            for a in &s.arguments {
                let mut libraries = a.argument.libraries_used.clone();
                if libraries.is_empty() {
                    libraries.push(a.argument.root_module.clone());
                }
                libraries.sort();
                libraries.dedup();
                rows.push(BankRow {
                    accession: a.argument.accession.clone(),
                    bank: "arguments".into(),
                    decl_name: a.argument.root_decl_name.clone(),
                    pretty: a.argument.root_pretty.clone(),
                    module: a.argument.root_module.clone(),
                    libraries,
                    author: a.argument.citation_name.clone(),
                    author_login: a.argument.login.clone(),
                    created_at: ts(&a.argument.created_at),
                    arguments: 1,
                    axioms: a.argument.axioms_reached.clone(),
                    axiom_free: a.argument.axiom_free,
                    nodes: a.argument.node_count as i64,
                    constants: a.argument.export_constants as i64,
                    claim_accession: Some(a.argument.claim_accession.clone()),
                });
            }
        }
    }
    rows
}

/// The public unit manifest, v3: the v2 shape with every internal-only field
/// removed and `witness` schema-constrained to `null` (SPEC.md §10).
fn manifest_for(s: &Snapshot, acc: &Accession) -> serde_json::Value {
    let key = acc.to_string();
    let dictionary = serde_json::json!({
        "label": s.dictionary.label,
        "export_sha256": s.dictionary.export_sha256,
        "toolchain": s.dictionary.toolchain,
        "mathlib_rev": s.dictionary.mathlib_rev,
        "flt_rev": s.dictionary.flt_rev,
        "curation": s.dictionary.curation,
        "blueprint_url": s.dictionary.blueprint_url,
    });
    match acc.kind {
        Kind::Claim => {
            let c = s.claim(&key).expect("a validated claim");
            let date = c.created_at.format("%Y-%m-%d").to_string();
            let cite = citation(&c.citation_name, &c.decl_name, acc, &s.site_base, &date);
            let args: Vec<String> = s
                .arguments_of(&key)
                .iter()
                .map(|a| a.argument.accession.clone())
                .collect();
            serde_json::json!({
                // v4 adds `doc`: the author's docstring, verbatim, or null.
                "schema": "mathesis/public-unit-manifest/v4",
                "doi": key,
                "kind": "claim",
                "decl_name": c.decl_name,
                "module": c.module,
                "doc": c.doc,
                "statement": {
                    "decl_names": [c.decl_name],
                    "pretty": c.pretty,
                    "type_sha256": c.statement_digest,
                },
                "arguments": args,
                "arguments_count": c.arguments_count,
                // Derived, never a stored column: an open claim is one nobody
                // has proved yet (R14).
                "is_open": c.arguments_count == 0,
                "origin": c.origin,
                "axiom_manifest": s.claim_axioms(&key),
                "verification": null,
                "dictionary": dictionary,
                "attribution": {
                    "citation_name": c.citation_name,
                    "profile_path": format!("/p/{}", c.profile_id),
                },
                "post_number": null,
                "citation": { "text": cite.text, "bibtex": cite.bibtex },
                "witness": null,
                "created": ts(&c.created_at),
            })
        }
        Kind::Argument => {
            let a = s.argument(&key).expect("a validated argument");
            let root = a
                .nodes
                .iter()
                .find(|n| n.is_root)
                .expect("a validated root");
            let date = a.argument.created_at.format("%Y-%m-%d").to_string();
            let cite = citation(
                &a.argument.citation_name,
                &a.argument.root_decl_name,
                acc,
                &s.site_base,
                &date,
            );
            let post = s
                .posts
                .iter()
                .find(|p| p.argument_accession == key)
                .map(|p| p.post_number);
            serde_json::json!({
                "schema": "mathesis/public-unit-manifest/v4",
                "doi": key,
                "kind": "argument",
                "decl_name": a.argument.root_decl_name,
                "module": a.argument.root_module,
                "doc": root.doc,
                "statement": {
                    "decl_names": a.nodes.iter().map(|n| n.decl_name.clone()).collect::<Vec<_>>(),
                    "pretty": a.argument.root_pretty,
                    "type_sha256": root.type_sha256,
                },
                "claim": a.argument.claim_accession,
                "is_open": false,
                "frozen_export": {
                    "path": format!("mathesis-exports/{}.export", a.argument.export_sha256),
                    "sha256": a.argument.export_sha256,
                    "bytes": a.argument.export_bytes,
                    "constants": a.argument.export_constants,
                },
                "axiom_manifest": a.argument.axioms_reached,
                "verification": {
                    "replay": "accepted",
                    "statement_identity": a.argument.statement_identity,
                    "substrate": a.argument.substrate,
                    // A non-null triviality is a rejection, so an admitted
                    // record always carries null; the field is emitted to state
                    // that the check ran (R7).
                    "triviality": null,
                    "gate_version": s.dictionary.adjudicate_image,
                },
                "dag": {
                    "node_count": a.argument.node_count,
                    "edge_count": a.argument.edge_count,
                    "dictionary_leaves": s.dictionary_leaves(a).into_iter().collect::<Vec<_>>(),
                    "nodes": a.nodes,
                    "edges": a.edges,
                },
                "dictionary": dictionary,
                "attribution": {
                    "citation_name": a.argument.citation_name,
                    "profile_path": format!("/p/{}", a.argument.profile_id),
                },
                "post_number": post,
                "citation": { "text": cite.text, "bibtex": cite.bibtex },
                "witness": null,
                "created": ts(&a.argument.created_at),
            })
        }
    }
}
