#!/usr/bin/env python3
"""Write tests/diff/KernelCheck.lean: case classes (a) and (b) of the differential test, in the kernel.

The differential test runs decode32 as compiled code. This checks the same words the way claims are
checked: in the kernel, by `decide`, against values printed by the C oracle (tests/diff/oracle.c),
never by decode32. There is one theorem per exponent field (class (a): 6 fractions x 2 signs = 12
words each), and one for class (b).

    python3 tests/diff/mkkernelcheck.py        then    lake env lean tests/diff/KernelCheck.lean
"""
import pathlib
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent


def oracle_values(oracle: pathlib.Path, words: list[int]) -> list[str]:
    out = subprocess.run([str(oracle)], input="".join(f"{w:08x}\n" for w in words),
                         capture_output=True, text=True, check=True).stdout.splitlines()
    assert len(out) == len(words)
    return out


def lean_value(line: str) -> str:
    """The oracle's `m e` (the value m * 2^e, m odd) as core's Dyadic: `.ofOdd m (-e) rfl`."""
    if line == "none":
        return "none"
    m, e = map(int, line.split())
    return "some .zero" if m == 0 else f"some (.ofOdd ({m}) ({-e}) rfl)"


def theorem(name: str, doc: str, words: list[int], values: list[str]) -> str:
    rows = ",\n      ".join(f"(0x{w:08X}, {lean_value(v)})" for w, v in zip(words, values))
    return (f"/-- {doc} -/\n"
            f"theorem {name} :\n"
            f"    ([{rows}] : List (Nat × Option Dyadic)).all\n"
            f"      (fun p => decode32 p.1 == p.2) = true := by\n"
            f"  decide\n")


def main() -> None:
    fractions = [0, 1, 2, 0x400000, 0x7FFFFE, 0x7FFFFF]
    with tempfile.TemporaryDirectory() as tmp:
        oracle = pathlib.Path(tmp) / "oracle"
        subprocess.run(["cc", "-O2", "-ffp-contract=off", "-fno-fast-math",
                        str(HERE / "oracle.c"), "-lm", "-o", str(oracle)], check=True)
        parts = [
            "import StetData.Float32\n\n"
            "/-!\n"
            "# Case classes (a) and (b), in the kernel\n\n"
            "Generated by `tests/diff/mkkernelcheck.py`. Each expected value was printed by the C oracle\n"
            "(`tests/diff/oracle.c`), not by `decode32`; `.ofOdd m k _` is the value `m · 2^(−k)`.\n"
            "-/\n"
        ]
        for e in range(256):
            words = [(s << 31) | (e << 23) | f for s in (0, 1) for f in fractions]
            parts.append(theorem(f"kernel_exponent_{e:02x}",
                                 f"Class (a), exponent field 0x{e:02X}: six fractions, both signs.",
                                 words, oracle_values(oracle, words)))
        nan_words = [(s << 31) | (255 << 23) | f for s in (0, 1) for f in (1, 0x400000, 0x7FFFFF)]
        parts.append(theorem("kernel_nan_boundaries",
                             "Class (b): every NaN boundary, both signs.",
                             nan_words, oracle_values(oracle, nan_words)))
    (HERE / "KernelCheck.lean").write_text("\n".join(parts))


if __name__ == "__main__":
    main()
