// GENERATED by npm run gen:reasons from shared/reasons.v1.json. Do not edit.
export type ReasonCode =
  | "SOURCE_TOO_LARGE"
  | "SOURCE_NOT_UTF8"
  | "PRELUDE_MODIFIED"
  | "NAMESPACE_MODIFIED"
  | "EXTRA_IMPORT"
  | "CLAIM_DECL_INVALID"
  | "CLAIM_NOT_DECLARED"
  | "CLAIM_DECL_MISMATCH"
  | "PROVES_DOI_INVALID"
  | "PROVES_DOI_UNKNOWN"
  | "PROVES_DOI_NO_REFERENCE"
  | "DICT_PIN_STALE"
  | "PROFILE_KIND_UNSET"
  | "IDE_SESSION_REQUIRED"
  | "IDE_SESSION_UNKNOWN"
  | "IDE_SESSION_NOT_OWNED"
  | "IDE_BUFFER_MISMATCH"
  | "RATE_LIMITED"
  | "TITLE_MISSING"
  | "CLAIM_NOT_CHOSEN"
  | "PRELUDE_DECLARED"
  | "COMMAND_NOT_ACCEPTED"
  | "IMPORT_NOT_LEADING"
  | "IMPORT_INVALID"
  | "IMPORTS_DIFFER"
  | "STATEMENT_DECLARES_NOTHING"
  | "PROOF_DECL_MISSING"
  | "PROOF_LEAVES_GAP"
  | "BUILD_FAILED"
  | "BUILD_TIMEOUT"
  | "BUILD_OOM"
  | "EXPORT_FAILED"
  | "EXPORT_PANIC"
  | "EXPORT_EMPTY"
  | "EXPORT_TOO_LARGE"
  | "EXPORT_TIMEOUT"
  | "EXPORT_MALFORMED"
  | "REPLAY_REJECTED"
  | "ILLEGAL_AXIOM"
  | "AXIOM_SPOOFED"
  | "TRUSTED_CONSTANT_REDEFINED"
  | "STATEMENT_IDENTITY_FAILED"
  | "TARGET_ABSENT"
  | "CLAIM_TRIVIAL"
  | "CONSTANT_NOT_IN_DICTIONARY"
  | "DICTIONARY_CONSTANT_REDEFINED"
  | "BASE_CONSTANT_REDEFINED"
  | "NEW_AXIOM"
  | "NEW_DEFINITION"
  | "NEW_OPAQUE"
  | "NEW_INDUCTIVE"
  | "NEW_QUOT"
  | "DECLARATION_OUTSIDE_SUBMISSION"
  | "PRIVATE_DEF_IN_STATEMENT"
  | "CLAIM_NOT_A_THEOREM"
  | "CLAIM_ABSENT"
  | "DAG_CYCLE"
  | "RENDER_MISSING_STATEMENT"
  | "DICTIONARY_DIVERGENCE"
  | "CLAIM_DIGEST_MISMATCH"
  | "REGISTRY_UNAVAILABLE"
  | "INFRA_TRUST_BASE_EMPTY"
  | "INFRA_REPORT_EXIT_MISMATCH"
  | "INFRA_REFERENCE_FETCH_FAILED"
  | "INFRA_BLOB_UPLOAD_FAILED"
  | "INFRA_COLLECTOR_POST_FAILED"
  | "INFRA_RENDER_FAILED"
  | "INFRA_JOB_DEADLINE"
  | "INFRA_NODE_EVICTED"
  | "INFRA_QUOTA_EXCEEDED"
  | "INFRA_IMAGE_PULL"
  | "INFRA_PVC_UNBOUND";

const TEMPLATES: Record<ReasonCode, string> = {
  "SOURCE_TOO_LARGE": "Source is {bytes} bytes; the limit is {limit}.",
  "SOURCE_NOT_UTF8": "Source is not UTF-8 at byte {offset}.",
  "PRELUDE_MODIFIED": "Line 1 must be the prelude import of the dictionary module.",
  "NAMESPACE_MODIFIED": "The Submission namespace wrapper is altered at line {line}.",
  "EXTRA_IMPORT": "An import outside the prelude appears at line {line}.",
  "CLAIM_DECL_INVALID": "The designated name {decl} is not a valid declaration name.",
  "CLAIM_NOT_DECLARED": "The buffer declares no theorem named {decl}.",
  "CLAIM_DECL_MISMATCH": "The designated claim must be declared as {required}.",
  "PROVES_DOI_INVALID": "The accession {doi} is not a well-formed claim accession.",
  "PROVES_DOI_UNKNOWN": "No claim carries the accession {doi}.",
  "PROVES_DOI_NO_REFERENCE": "The claim {doi} carries no reference export.",
  "DICT_PIN_STALE": "The submitted pin is not the active pin {active}.",
  "PROFILE_KIND_UNSET": "The submitting profile has declared no profile kind.",
  "IDE_SESSION_REQUIRED": "A submission carries no editor session identifier.",
  "IDE_SESSION_UNKNOWN": "The editor session {session} does not exist.",
  "IDE_SESSION_NOT_OWNED": "The editor session {session} belongs to another profile.",
  "IDE_BUFFER_MISMATCH": "Editor buffer {ide_sha256} differs from submitted buffer {buffer_sha256}.",
  "RATE_LIMITED": "Too many in-flight verifications; retry after {retry_after_s} seconds.",
  "TITLE_MISSING": "The submission carries no title.",
  "CLAIM_NOT_CHOSEN": "No claim is chosen to prove.",
  "PRELUDE_DECLARED": "The {part} declares prelude at line {line}; a deposit builds on the standard prelude.",
  "COMMAND_NOT_ACCEPTED": "The {part} runs {command} at line {line}; a deposit runs no code while it builds.",
  "IMPORT_NOT_LEADING": "The import at line {line} of the {part} follows other source; imports come first.",
  "IMPORT_INVALID": "The import {module} is not a dotted module name.",
  "IMPORTS_DIFFER": "The statement imports {statement} and the proof imports {proof}; both parts share one list.",
  "STATEMENT_DECLARES_NOTHING": "The statement declares no theorem.",
  "PROOF_DECL_MISSING": "The proof declares no theorem named {decl}.",
  "PROOF_LEAVES_GAP": "The proof leaves {tactic} at line {line}.",
  "BUILD_FAILED": "Elaboration exited {exit_code}; the compiler output is the reason.",
  "BUILD_TIMEOUT": "Elaboration exceeded {seconds} seconds.",
  "BUILD_OOM": "Elaboration exceeded the memory limit {limit}.",
  "EXPORT_FAILED": "The exporter exited {exit_code}.",
  "EXPORT_PANIC": "The exporter reported a panic or an internal error.",
  "EXPORT_EMPTY": "The exporter produced an empty export.",
  "EXPORT_TOO_LARGE": "The export is {bytes} bytes; the limit is {limit}.",
  "EXPORT_TIMEOUT": "The exporter exceeded {seconds} seconds.",
  "EXPORT_MALFORMED": "The export could not be parsed: {detail}.",
  "REPLAY_REJECTED": "Kernel replay rejected the export: {detail}.",
  "ILLEGAL_AXIOM": "The closure reaches the axiom {axiom}, outside the whitelist.",
  "AXIOM_SPOOFED": "The axiom {axiom} does not carry its kernel type.",
  "TRUSTED_CONSTANT_REDEFINED": "The trusted constant {constant} is redefined by the export.",
  "STATEMENT_IDENTITY_FAILED": "Statement identity failed: {detail}.",
  "TARGET_ABSENT": "The reference target {decl} is absent from the export.",
  "CLAIM_TRIVIAL": "The designated claim is degenerate: {detail}.",
  "CONSTANT_NOT_IN_DICTIONARY": "The constant {constant} of module {module} is not a dictionary entry.",
  "DICTIONARY_CONSTANT_REDEFINED": "The dictionary constant {constant} is redefined by the export.",
  "BASE_CONSTANT_REDEFINED": "The base constant {constant} is redeclared by the export.",
  "NEW_AXIOM": "The export declares a new axiom {constant}.",
  "NEW_DEFINITION": "The export declares a new definition {constant}.",
  "NEW_OPAQUE": "The export declares a new opaque constant {constant}.",
  "NEW_INDUCTIVE": "The export declares a new inductive type {constant}.",
  "NEW_QUOT": "The export declares a new quotient constant {constant}.",
  "DECLARATION_OUTSIDE_SUBMISSION": "The declaration {constant} lies outside the Submission namespace.",
  "PRIVATE_DEF_IN_STATEMENT": "The claim statement rests on the private helper {constant}.",
  "CLAIM_NOT_A_THEOREM": "The designated claim is a {kind}, not a theorem.",
  "CLAIM_ABSENT": "The designated claim {decl} is absent from the export.",
  "DAG_CYCLE": "The sub-argument graph carries a cycle through {names}.",
  "RENDER_MISSING_STATEMENT": "The renderer emitted no statement for {decl}.",
  "DICTIONARY_DIVERGENCE": "The constant {constant} diverges from the pinned dictionary.",
  "CLAIM_DIGEST_MISMATCH": "The statement is already claim {claim_accession}; declare {required_decl_name}.",
  "REGISTRY_UNAVAILABLE": "The registry did not answer.",
  "INFRA_TRUST_BASE_EMPTY": "The trusted base {path} is absent or empty.",
  "INFRA_REPORT_EXIT_MISMATCH": "Exit {exit_code} disagrees with the posted verdict {verdict}.",
  "INFRA_REFERENCE_FETCH_FAILED": "The reference blob {sha256} could not be fetched.",
  "INFRA_BLOB_UPLOAD_FAILED": "The export blob {sha256} could not be stored.",
  "INFRA_COLLECTOR_POST_FAILED": "The collector answered {status}.",
  "INFRA_RENDER_FAILED": "The renderer exited {exit_code}.",
  "INFRA_JOB_DEADLINE": "The job {job} passed its active deadline.",
  "INFRA_NODE_EVICTED": "The job {job} was evicted from its node.",
  "INFRA_QUOTA_EXCEEDED": "The namespace {namespace} quota refused the job.",
  "INFRA_IMAGE_PULL": "The image {image} could not be pulled.",
  "INFRA_PVC_UNBOUND": "The volume claim {pvc} stayed unbound."
} as Record<ReasonCode, string>;

export const REASON_CODES: ReasonCode[] = ["SOURCE_TOO_LARGE","SOURCE_NOT_UTF8","PRELUDE_MODIFIED","NAMESPACE_MODIFIED","EXTRA_IMPORT","CLAIM_DECL_INVALID","CLAIM_NOT_DECLARED","CLAIM_DECL_MISMATCH","PROVES_DOI_INVALID","PROVES_DOI_UNKNOWN","PROVES_DOI_NO_REFERENCE","DICT_PIN_STALE","PROFILE_KIND_UNSET","IDE_SESSION_REQUIRED","IDE_SESSION_UNKNOWN","IDE_SESSION_NOT_OWNED","IDE_BUFFER_MISMATCH","RATE_LIMITED","TITLE_MISSING","CLAIM_NOT_CHOSEN","PRELUDE_DECLARED","COMMAND_NOT_ACCEPTED","IMPORT_NOT_LEADING","IMPORT_INVALID","IMPORTS_DIFFER","STATEMENT_DECLARES_NOTHING","PROOF_DECL_MISSING","PROOF_LEAVES_GAP","BUILD_FAILED","BUILD_TIMEOUT","BUILD_OOM","EXPORT_FAILED","EXPORT_PANIC","EXPORT_EMPTY","EXPORT_TOO_LARGE","EXPORT_TIMEOUT","EXPORT_MALFORMED","REPLAY_REJECTED","ILLEGAL_AXIOM","AXIOM_SPOOFED","TRUSTED_CONSTANT_REDEFINED","STATEMENT_IDENTITY_FAILED","TARGET_ABSENT","CLAIM_TRIVIAL","CONSTANT_NOT_IN_DICTIONARY","DICTIONARY_CONSTANT_REDEFINED","BASE_CONSTANT_REDEFINED","NEW_AXIOM","NEW_DEFINITION","NEW_OPAQUE","NEW_INDUCTIVE","NEW_QUOT","DECLARATION_OUTSIDE_SUBMISSION","PRIVATE_DEF_IN_STATEMENT","CLAIM_NOT_A_THEOREM","CLAIM_ABSENT","DAG_CYCLE","RENDER_MISSING_STATEMENT","DICTIONARY_DIVERGENCE","CLAIM_DIGEST_MISMATCH","REGISTRY_UNAVAILABLE","INFRA_TRUST_BASE_EMPTY","INFRA_REPORT_EXIT_MISMATCH","INFRA_REFERENCE_FETCH_FAILED","INFRA_BLOB_UPLOAD_FAILED","INFRA_COLLECTOR_POST_FAILED","INFRA_RENDER_FAILED","INFRA_JOB_DEADLINE","INFRA_NODE_EVICTED","INFRA_QUOTA_EXCEEDED","INFRA_IMAGE_PULL","INFRA_PVC_UNBOUND"] as ReasonCode[];

/** Renders a deterministic reason. Reason messages are error messages and are
 * the one class of visible string outside the label catalogue. */
export function renderReason(code: string, params: Record<string, unknown>): string {
  const t = TEMPLATES[code as ReasonCode];
  if (!t) return code;
  return t.replace(/\{(\w+)\}/g, (_m, k) => {
    const v = params[k];
    return v === undefined || v === null ? "—" : String(v);
  });
}
